TRUNCATE imagem;
INSERT INTO imagem (caminho, nome, tipo, is_ativo, data_upload, id_buffet) VALUES
('https://s3-eventify-arquivos.s3.amazonaws.com/img/', '11_2-min', 'webp', NOW(), id_buffet),
('https://s3-eventify-arquivos.s3.amazonaws.com/img/', '11_1-min', 'webp', NOW(), id_buffet),
('https://s3-eventify-arquivos.s3.amazonaws.com/img/', '12_3-min', 'webp', NOW(), id_buffet),
('https://s3-eventify-arquivos.s3.amazonaws.com/img/', '12_2-min', 'webp', NOW(), id_buffet),
('https://s3-eventify-arquivos.s3.amazonaws.com/img/', '12_1-min', 'webp', NOW(), id_buffet),
('https://s3-eventify-arquivos.s3.amazonaws.com/img/', '13_2-min', 'webp', NOW(), id_buffet),
('https://s3-eventify-arquivos.s3.amazonaws.com/img/', '13_3-min', 'webp', NOW(), id_buffet),
('https://s3-eventify-arquivos.s3.amazonaws.com/img/', '13_1-min', 'webp', NOW(), id_buffet),
('https://s3-eventify-arquivos.s3.amazonaws.com/img/', '14_3-min', 'webp', NOW(), id_buffet),
('https://s3-eventify-arquivos.s3.amazonaws.com/img/', '14_1-min', 'webp', NOW(), id_buffet),
('https://s3-eventify-arquivos.s3.amazonaws.com/img/', '14_2-min', 'webp', NOW(), id_buffet),
('https://s3-eventify-arquivos.s3.amazonaws.com/img/', '15_1-min', 'webp', NOW(), id_buffet),
('https://s3-eventify-arquivos.s3.amazonaws.com/img/', '15_3-min', 'webp', NOW(), id_buffet),
('https://s3-eventify-arquivos.s3.amazonaws.com/img/', '15_2-min', 'webp', NOW(), id_buffet),
('https://s3-eventify-arquivos.s3.amazonaws.com/img/', 'DALL·E 2023-10-19 21.27.02 - Photo of the Buffet do Chef dining hall, showcasing a more organic layout with tables arranged in a non-uniform manner. The decor is elegant yet und-min', 'webp', NOW(), id_buffet),
('https://s3-eventify-arquivos.s3.amazonaws.com/img/', 'DALL·E 2023-10-19 21.27.03 - Photo of a corner of Buffet do Chef where guests are gathered around a live cooking station. The ambiance is cozy with a mix of modern and classic d-min', 'webp', NOW(), id_buffet),
('https://s3-eventify-arquivos.s3.amazonaws.com/img/', 'DALL·E 2023-10-19 21.27.06 - Photo of a well-lit Buffet do Chef venue featuring a diverse buffet spread. The area has a mix of high and low seating arrangements, with a few gues-min', 'webp', NOW(), id_buffet),
('https://s3-eventify-arquivos.s3.amazonaws.com/img/', 'DALL·E 2023-10-19 21.27.05 - Photo of an outdoor extension of the Buffet do Chef, offering a more relaxed setting. There are string lights overhead, and guests are seen enjoying-min', 'webp', NOW(), id_buffet),
('https://s3-eventify-arquivos.s3.amazonaws.com/img/', 'DALL·E 2023-10-19 21.29.41 - Photo of the Buffet Vice Feeling dining hall, inspired by the 1980s California vibe. The room features neon lights, retro posters, and vintage furni-min', 'webp', NOW(), id_buffet),
('https://s3-eventify-arquivos.s3.amazonaws.com/img/', 'DALL·E 2023-10-19 21.29.43 - Photo of an outdoor patio of Buffet Vice Feeling, decorated with string lights and vintage lounge chairs. Guests are enjoying the evening, with the -min', 'webp', NOW(), id_buffet),
('https://s3-eventify-arquivos.s3.amazonaws.com/img/', 'DALL·E 2023-10-19 21.29.39 - Photo of a section of Buffet Vice Feeling showcasing a dance floor with a disco ball overhead. The ambiance is reminiscent of a Californian beachsid-min', 'webp', NOW(), id_buffet),
('https://s3-eventify-arquivos.s3.amazonaws.com/img/', 'DALL·E 2023-10-19 21.32.24 - Photo of the Sabor e Arte Buffet dining area, designed for corporate events. Round tables are set with elegant dishes, and a few attendees are seen -min', 'webp', NOW(), id_buffet),
('https://s3-eventify-arquivos.s3.amazonaws.com/img/', 'DALL·E 2023-10-19 21.32.27 - Photo of an outdoor extension of Sabor e Arte Buffet, designed for corporate break sessions. Diverse attendees are seated in lounge areas, enjoying -min', 'webp', NOW(), id_buffet),
('https://s3-eventify-arquivos.s3.amazonaws.com/img/', 'DALL·E 2023-10-19 21.32.28 - Photo of the Sabor e Arte Buffet with a dedicated presentation area. As attendees listen to a speaker, some are seen at the back enjoying snacks fro-min', 'webp', NOW(), id_buffet),
('https://s3-eventify-arquivos.s3.amazonaws.com/img/', 'DALL·E 2023-10-19 21.32.25 - Photo of a buffet station at Sabor e Arte Buffet where a variety of gourmet dishes are displayed. Attendees of various genders and descents are in l-min', 'webp', NOW(), id_buffet),
('https://s3-eventify-arquivos.s3.amazonaws.com/img/', 'DALL·E 2023-10-19 21.34.38 - Photo of the Delícias da Vovó buffet hall, exuding a homely ambiance. Wooden tables are adorned with traditional checkered tablecloths, and theres -min', 'webp', NOW(), id_buffet),
('https://s3-eventify-arquivos.s3.amazonaws.com/img/', 'DALL·E 2023-10-19 21.34.35 - Photo of an outdoor patio of Delícias da Vovó, featuring a cozy setting with hanging lanterns and long tables. Guests are enjoying traditional dishe-min', 'webp', NOW(), id_buffet),
('https://s3-eventify-arquivos.s3.amazonaws.com/img/', 'DALL·E 2023-10-19 21.34.36 - Photo of the Delícias da Vovó buffet venue, designed to feel like a family gathering at grandmas house. Theres a rustic charm with wooden beams, a-min', 'webp', NOW(), id_buffet),
('https://s3-eventify-arquivos.s3.amazonaws.com/img/', 'DALL·E 2023-10-19 21.34.40 - Photo of a dining area in Delícias da Vovó with vintage decor and family portraits on the walls. The buffet counter is laden with pots and pans cont-min', 'webp', NOW(), id_buffet),
('https://s3-eventify-arquivos.s3.amazonaws.com/img/', 'DALL·E 2023-10-19 21.38.42 - Photo of the Buffet Festivo hall, tailored for birthday celebrations. The room is festively decorated with colorful balloons, banners, and a central-min', 'png', NOW(), id_buffet),
('https://s3-eventify-arquivos.s3.amazonaws.com/img/', 'DALL·E 2023-10-19 21.36.33 - Photo of a dining area in Buffet Festivo with long tables set for a birthday feast. The buffet counter showcases a variety of dishes suitable for al-min', 'png', NOW(), id_buffet),
('https://s3-eventify-arquivos.s3.amazonaws.com/img/', 'DALL·E 2023-10-23 17.55.40 - Photo capturing the opulence of Sabores Exóticos. The buffet table stands out with dishes from diverse world cuisines, set against a backdrop of dra-min', 'png', NOW(), id_buffet),
('https://s3-eventify-arquivos.s3.amazonaws.com/img/', 'DALL·E 2023-10-23 17.55.48 - Professional snapshot of the Sabores Exóticos event venue. The buffet, with plates piled high with exotic food, is the centerpiece. Floral arrangeme-min', 'png', NOW(), id_buffet),
('https://s3-eventify-arquivos.s3.amazonaws.com/img/', 'DALL·E 2023-10-23 17.58.44 - Photo of a serene beachside venue named Buffet da Praia. The setting showcases tables set up on the sandy shore, laden with dishes that resonate wit-min', 'png', NOW(), id_buffet),
('https://s3-eventify-arquivos.s3.amazonaws.com/img/', 'DALL·E 2023-10-23 17.57.53 - Photograph of a bustling event at Buffet da Praia. The sandy venue is dotted with dining setups, where attendees savor coastal dishes. The horizon w-min', 'png', NOW(), id_buffet),
('https://s3-eventify-arquivos.s3.amazonaws.com/img/', 'DALL·E 2023-10-23 18.52.05 - Photo of a vibrant party venue named Festas Divertidas. The setting displays various themed stations tailored for childrens parties. From a pirate -min', 'png', NOW(), id_buffet),
('https://s3-eventify-arquivos.s3.amazonaws.com/img/', 'DALL·E 2023-10-23 18.51.31 - Professional photograph of Festas Divertidas event space. The venue is buzzing with thematic setups like a superhero section, a princess castle, and-min', 'png', NOW(), id_buffet),
('https://s3-eventify-arquivos.s3.amazonaws.com/img/', '9_3-min', 'webp', NOW(), id_buffet),
('https://s3-eventify-arquivos.s3.amazonaws.com/img/', '9_2-min', 'webp', NOW(), id_buffet),
('https://s3-eventify-arquivos.s3.amazonaws.com/img/', '9_1-min', 'webp', NOW(), id_buffet),
('https://s3-eventify-arquivos.s3.amazonaws.com/img/', '10_2-min', 'webp', NOW(), id_buffet),
('https://s3-eventify-arquivos.s3.amazonaws.com/img/', '10_3-min', 'webp', NOW(), id_buffet),
('https://s3-eventify-arquivos.s3.amazonaws.com/img/', '10_1-min', 'webp', NOW(), id_buffet);
